version: '3'
services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    networks:
      - network

  anime:
    image: talissonmelo/anime:latest
    restart: always
    depends_on:
    - db
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USERNAME: root
      DB_PASSWORD: 123456
    networks:
      - network

networks:
  network:
    driver: bridge